#!/usr/bin/env python3
"""Fake `aws` CLI for the deploy script test: logs calls, answers the reads."""

import json
import os
import sys

argv = sys.argv[1:]
with open(os.environ["FAKE_AWS_LOG"], "a") as f:
    f.write(json.dumps(argv) + "\n")

if "get-caller-identity" in argv:
    print("333344445555")
elif "configure" in argv:
    print(os.environ.get("FAKE_REGION", ""))
elif "head-bucket" in argv and os.environ.get("FAKE_BUCKET_EXISTS") != "1":
    sys.exit(254)
